### ISSUE TITLE
Ability to cache results? Very slow performance

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/com.unity.formats.alembic#227]
The alembic plugin works in principle, but performance for large files is really slow (5-10 fps).

I do understand that playback might not be smooth on the first run, but I would like to see an option to keep mesh results in RAM, because right now it's pretty difficult to play back large files since it seems all meshes are re-uploaded every frame.

Deleting objects from the scene results in these meshes still being calculated, so there is no current way to optimize performance than to split/optimize the alembic file itself, which I'd like to avoid.

- .abc file or project data that can reproduce the issue
I can share that in private if you send me a mail address / a way to transfer it non-publicly. It's a 500MB abc file with 60 frames.
- version of AlembicForUnity you are using
20180205

**Comment by clusty** [comment]
Sorry for the late reply.
We are aware of the performance problems with alembics. I cannot give you a timeline however as to when they will be fixed.
For now I think the best you can do is optimize it by hand unfortunately.

**Comment by soraryu** [comment]
Thanks for the reply.

I ended up writing a brute-force Mesh cache script that basically buffers all generated Alembic meshes and, if that specific frame has been used before, just uses the buffered mesh instead of the Alembic file.
This is super unoptimized though as it saves a full copy of the whole mesh each frame, even if the object is static.

(you can see the caching in action here: https://herbst.itch.io/jumping-rabbit - basically with the alembic plugin performance is somewhere around 1-2fps, with caching it goes back to 60 but obviously eats a ton of RAM)

**Comment by cguer** [comment]
Hello! In order to centralize support for the Alembic package, the Unity team has decided to close the `Issues` section of this repository.

While several small performance improvements have been made over the years we have still not tackled a more generic "vertex cache" solution. We still can't promise anything around that area but be assured that your request is still logged in our internal tracker for potential future development. 

For future support requests, you can either:

- Post you question on the official [Unity Forum](https://forum.unity.com/forums/virtual-production.466/) using the alembic tag
- Report an issue directly inside the Unity Editor using the [Bug Report tool](https://unity.com/releases/editor/qa/bug-reporting)
