### ISSUE TITLE
Unity does not display alembic file created in Cinema 4d using xparticles.

### ISSUE THREAD

**Issue by amandalangley** [Unity-Technologies/com.unity.formats.alembic#260]
UPDATE: I finally got this to work for both xparticles and regular particles. What I did was start at frame 1 when exporting to alembic from Cinema4d. For some reason the object was getting lost when I started at frame 0. Maybe this will help someone. 

I created an Xparticles (plugin) system in C4d. UPDATE: I also tried with a normal particle emitter in C4d and had the same issue. I was able to export the .abc file and open it up in blender, but when I import into unity with AlembicForUnity, I do not see anything in the scene. 

I can import .abc files into Unity created in Cinema4D. I added some morphing and that worked as well. I am using the stable version on Unity 2019. Cinema 4d 20. Mac Mojave.  I've attached the .abc file.
[pyra.abc.zip](https://github.com/unity3d-jp/AlembicForUnity/files/3123164/pyra.abc.zip)

I have searched around and I think other people are able to use Xparticles with alembic to unity, so perhaps I am missing something. 

- what version of package 1.0.3

**Comment by JoelFortin** [comment]
@amandalangley  ... I looked at your file and realized that there was no material assign to it. If you import your attached file in Unity and increase the Materials Size property to 1, you'll see your particles.

Now something else seems to happen here, the so called particles exported from C4D aren't considered particles by the Unity Alembic importer, otherwise we would have got a Alembic Point Renderer assign the the object instead of a Mesh Renderer. The fact that no material is assign is something we should look at for the alembic importer but from the C4D, it seems that xparticles aren't exported as "particles" or maybe "Export Particle Shape as Mesh" export option is used in this particular case.

**Comment by JoelFortin** [comment]
The problem has been submitted to our internal database:
https://unity3d.atlassian.net/browse/FTV-166
