### ISSUE TITLE
WebGL support

### ISSUE THREAD

**Issue by qu4sar** [Unity-Technologies/com.unity.formats.alembic#420]
I'm trying for different time to export for WebGL. Is it supported ? Thanks

**Comment by cguer** [comment]
Hello! In order to centralize support for the Alembic package, the Unity team has decided to close the `Issues` section of this repository.

The Alembic package currently only supports desktop build platforms (Windows, MacOS, Linux).

If you still require WebGL support, we encourage to vote on this feature on our [roadmap portal](https://portal.productboard.com/29hswdggfdmr5hcrptjlj24p/c/1357-alembic-alembic-at-runtime) and explain your use case. Your feedback is very important to us and directly impacts our future development decisions.

For future support requests, you can either:
- Post you question on the official [Unity Forum](https://forum.unity.com/forums/virtual-production.466/) using the alembic tag
- Report an issue directly inside the Unity Editor using the [Bug Report tool](https://unity.com/releases/editor/qa/bug-reporting)
