### ISSUE TITLE
Alembic that have vertex color animation crash Unity

### ISSUE THREAD

**Issue by ForteDexe** [Unity-Technologies/com.unity.formats.alembic#486]
Alembic track that have vertex color animation cause crash, while maya and other engine work fine.
Unity will crash immediately when drag the alembic track to timeline, no error log.
_Alembic package 2.2.2
_Unity version 2020.3.0f1
[output.zip](https://github.com/Unity-Technologies/com.unity.formats.alembic/files/7207511/output.zip)

**Comment by cguer** [comment]
Hello! Your issue has been logged into our internal database for tracking but in order to centralize support for the Alembic package, the Unity team has decided to close the `Issues` section of this repository.

If you require support on other issues you can instead:
- Post you question on the official [Unity Forum](https://forum.unity.com/forums/virtual-production.466/) using the `alembic` tag
- Report an issue directly inside the Unity Editor using the [Bug Report tool](https://unity.com/releases/editor/qa/bug-reporting)
