### ISSUE TITLE
Alembic importing with n-1 frames

### ISSUE THREAD

**Issue by Zai-shen** [Unity-Technologies/com.unity.formats.alembic#487]
Could it be, that .abc's from Blender are importet with **[n-1]** frames?

I am trying to get a 2 second fluid animation out of it, therefore I have the start frame 1, end frame 48 set in Blender & Export settings. But when importing with this asset it shows a time range from 0.04166667 to 2, being 1.958... seconds, which in turn is the duration of 47 frames (at 24 fps).

Maybe I am overlooking something, but according to blender docs 48 frames should be in the .abc.

- I am using version 2.2.2.
- Unity 2020.3.10f
- Blender 2.93.4

**Comment by clusty** [comment]
Is this inside the importer or the timeline track ?

**Comment by Zai-shen** [comment]
In the importer iirc.

**Comment by cguer** [comment]
Hey @Zai-shen! The short version is that this is normal and you should still have access to all the timesamples in your Alembic file.

To calculate the length of an animation in Blender/Maya, we would do `numberOfFrame * 1/FPS`.
Using your example, the range 1-48 is a total of 48 frames -> `48 * 1/24` = 2 seconds

Alembic files don't store actual frames but instead timesamples (in seconds). The last Timesample in the file only represents a fixed data point in time _without_ a duration. The duration of that last timesample depends on the framerate of the software that will reads the Alembic file.

Ideally, we would calculate a more accurate duration using `(LastTimeSample + 1/FPS) - FirstTimeSample)` but Alembic files don't store the FPS at which they were exported at so this is unfortunately not possible.

Because we don't know how the export FPS or how long that last timesample will be "played" for, we can't display a more "accurate" duration.

Hopefully that explanation makes sense but ultimately you should still have access to the whole range of your Alembic file. Let us know if you still have questions or issues about this!
