### ISSUE TITLE
How to get the alembic vertex position data in C# code

### ISSUE THREAD

**Issue by stranger-games** [Unity-Technologies/com.unity.formats.alembic#501]
Hi,

I want to write a custom script and shader that would use position data of an object from alembic file.

I believe that the plugin currently won't allow me to directly access the data I need. Almost all classes are private to the package except the stream player.

I imagine I would need access to AlembicStreamDescriptor and would implement a custom version of AlembicStream.

A more involved solution would be to have a more generic version of AlembicStream with the current AlembicStream using it. That would help greatly with custom implementations for anyone interested.

I imagine the generic AlembicStream will have something like this

        void AbcBeginSyncData(AlembicTreeNode node)
        {
            if (node != null && node.abcObject != null && node.gameObject != null)
                listener.AbcSyncDataBegin(node);//node.abcObject can be null with the generic alembic stream. We can have an enum AlembicTreeNode.AlembicElementType (mesh or points, etc..) and the listener should have somehow access to the vertex, uv, .. data of that node to do its processing
            foreach (var child in node.Children)
                AbcBeginSyncData(child);
        }

        void AbcEndSyncData(AlembicTreeNode node)
        {
            if (node.abcObject != null && node.gameObject != null)
                listener.AbcSyncDataEnd(node);
            foreach (var child in node.Children)
                AbcEndSyncData(child);
        }

Thanks for advance.

**Comment by cguer** [comment]
Hello! In order to centralize support for the Alembic package, the Unity team has decided to close the `Issues` section of this repository.

If you still require support this issue, you can either:
- Post you question on the official [Unity Forum](https://forum.unity.com/forums/virtual-production.466/) using the `alembic` tag
- Report an issue directly inside the Unity Editor using the [Bug Report tool](https://unity.com/releases/editor/qa/bug-reporting)
